name: "Deploy 'main' branch to GitHub Pages"

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Inject GitHub Personal Access Token"
        run: |
          sed -i "s/PASTE_YOUR_NEW_TOKEN_HERE/${{ secrets.INDEXDOTHTML_OWNER_TOKEN_GITHUB_PERSONAL_ACCESS_TOKEN_GISTS }}/g" index.html

      - name: "Configure GitHub Pages"
        uses: actions/configure-pages@v4

      - name: "Upload GitHubPages Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: "Deploy to GitHub Pages"
        uses: actions/deploy-pages@v4
        id: deployment